package pizzamafia.CMbackend.enums;

public enum Ruolo {
    PORTIERE,
    DIFENSORE_CENTRALE,
    TERZINO,
    CENTROCAMPISTA_DIFENSIVO,
    CENTROCAMPISTA_CENTRALE,
    CENTROCAMPISTA_OFFENSIVO,
    ALA,
    ATTACCANTE_ESTERNO,
    BOMBER,
    SECONDA_PUNTA
}

