package pizzamafia.CMbackend.enums;

public enum Ruolo {
    PORTIERE,
    DIFENSORE_CENTRALE,
    TERZINO_DX,
    TERZINO_SX,
    CENTROCAMPISTA_DIFENSIVO,
    CENTROCAMPISTA_CENTRALE,
    CENTROCAMPISTA_OFFENSIVO,
    ALA_DX,
    ALA_SX,
    ATTACCANTE_ESTERNO_DX,
    ATTACCANTE_ESTERNO_SX,
    BOMBER,
    SECONDA_PUNTA
}

